# Generated by Django 4.1 on 2023-08-27 10:14

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import faceback.models
import pathlib
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("account", models.CharField(max_length=30, verbose_name="account")),
                ("password", models.CharField(max_length=30, verbose_name="password")),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update_time"),
                ),
                (
                    "date_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="date_time"),
                ),
            ],
            options={
                "verbose_name": "userinformation",
                "verbose_name_plural": "userinformation",
                "db_table": "userinfo",
            },
        ),
        migrations.CreateModel(
            name="UserTesteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_image",
                    models.ImageField(
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="/media/",
                            location=pathlib.PureWindowsPath(
                                "E:/facenet_app/backend/media"
                            ),
                        ),
                        upload_to=faceback.models.test_directory_path,
                        verbose_name="test_image",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faceback.userinfo",
                        verbose_name="test",
                    ),
                ),
            ],
            options={
                "verbose_name": "usertestimage",
                "verbose_name_plural": "usertestimage",
                "db_table": "usertestimage",
            },
        ),
        migrations.CreateModel(
            name="UserFaceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "face_image",
                    models.ImageField(
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="/media/",
                            location=pathlib.PureWindowsPath(
                                "E:/facenet_app/backend/media"
                            ),
                        ),
                        upload_to=faceback.models.user_directory_path,
                        verbose_name="face_image",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faceback.userinfo",
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "userfaceimage",
                "verbose_name_plural": "userfaceimage",
                "db_table": "userfaceimage",
            },
        ),
    ]
