# Generated by Django 4.1 on 2023-08-30 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("faceback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfaceimage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="faceback.userinfo",
            ),
        ),
        migrations.AlterField(
            model_name="usertesteimage",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test",
                to="faceback.userinfo",
            ),
        ),
    ]
