# Generated by Django 4.1 on 2023-08-31 08:47

import django.core.files.storage
from django.db import migrations, models
import faceback.models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("faceback", "0002_alter_userfaceimage_user_alter_usertesteimage_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfaceimage",
            name="face_image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location=pathlib.PureWindowsPath("E:/facenet_app/media"),
                ),
                upload_to=faceback.models.user_directory_path,
                verbose_name="face_image",
            ),
        ),
        migrations.AlterField(
            model_name="usertesteimage",
            name="test_image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location=pathlib.PureWindowsPath("E:/facenet_app/media"),
                ),
                upload_to=faceback.models.test_directory_path,
                verbose_name="test_image",
            ),
        ),
    ]
