# Generated by Django 4.1 on 2023-08-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faceback", "0003_alter_userfaceimage_face_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
